### ISSUE TITLE
俩bug report

### ISSUE THREAD

**Issue by xhzq233** [SmallJiu/JiuCore#1]
版本1.12.2
forge 14.23.5.2860
* [jiuCore.txt](https://github.com/SmallJiu/JiuCore/files/8771932/jiuCore.txt)
  这个关掉物品掉落就不crash了
* [crash-2022-05-25_22.14.37-server.txt](https://github.com/SmallJiu/JiuCore/files/8771944/crash-2022-05-25_22.14.37-server.txt)
  这个是打怪物的时候报错的，不会crash但是报错

**Comment by SmallJiu** [comment]
你是用什么来添加物品掉落的呢，如果是使用的json来添加的话，能不能提供下json的代码，如果是java的话，能不能提供下调用此方法(EntityDeathDrops.getDrops(EntityLivingBase)所在地方的代码；另一个下个小版本就会修。

**Comment by SmallJiu** [comment]
> 抱歉，没听太懂，就是正常模式下的被杀了然后玩家物品掉落（

就是说什么都没加，但是只要玩家死亡就会crash是吧

**Comment by xhzq233** [comment]
对的，不过会不会有跟其他mod冲突的可能？

**Comment by SmallJiu** [comment]
> 对的，不过会不会有跟其他mod冲突的可能？

如果是这种情况的话，已经知道怎么修了；不会，仅仅是我的问题，没有把玩家跟其他实体的死亡区分开

**Comment by xhzq233** [comment]
= =

**Comment by xhzq233** [comment]
那另一个问题怎么说

**Comment by SmallJiu** [comment]
> 那另一个问题怎么说

仅仅是我在写有meta的工具的时候没有考虑到mcs需要用到32766这个meta导致的

**Comment by SmallJiu** [comment]
> > 那另一个问题怎么说
> 
> 仅仅是我在写有meta的工具的时候没有考虑到mcs需要用到32766这个meta导致的

等我上传一下jar就行
